description: Alameda County accounts for these income sources when determining eligibility for the General Assistance program.
values:
  2024-01-01:
    # Employment income
    - irs_employment_income
    - self_employment_income
    # Social Security and disability benefits
    - social_security
    - ssi
    - ca_state_disability_insurance
    # Unemployment benefits
    - unemployment_compensation
    # Veterans benefits
    - veterans_benefits
    # Other public assistance (except those with dependent children)
    - tanf
    # CalWORKs (though typically for families with children)
    - ca_calworks
    # Any other cash assistance
    - other_income
metadata:
  unit: list
  period: year
  label: Alameda County General Assistance income sources
  reference:
    - title: Alameda County Social Services Agency - General Assistance
      href: https://www.alamedacountysocialservices.org/our-services/Work-and-Money/General-Assistance/index
    - title: Legal Services of Northern California - General Assistance
      href: https://lsnc.net/self-help/general-assistance-county-aid
