description: The Riverside Department of Community Action Partnership counts these income sources as countable income under the Low Income Home Energy Assistance Program.
values:
  2024-01-01:
    - employment_income
    - self_employment_income
    - alimony_income
    - child_support_received
    - pension_income
    - unemployment_compensation
    - social_security
    - ssi 
    - ca_tanf

metadata:
  unit: list
  period: year
  label: Riverside County LIHEAP countable income sources
  reference:
    - title: 2025 LIHEAP CAP APPLICATION ENGLISH.pdf
      href: https://capriverside.org/sites/g/files/aldnop136/files/2024-12/2025%20LIHEAP%20CAP%20APPLICATION%20ENGLISH.pdf#page=3
