description: Alameda County counts these assets toward the General Assistance personal property limit.
values:
  2024-01-01:
    # Cash and liquid assets
    - cash_assets
    - checking_account_balance
    - savings_account_balance
    # Other financial assets
    - stocks
    - bonds
    - mutual_funds
    # Personal property
    - vehicle_equity  # If not excluded
    - personal_property_value
    # Other countable assets
    - life_insurance_cash_value
    - retirement_account_balance  # If accessible
metadata:
  unit: list
  period: year
  label: Alameda County General Assistance counted asset sources
  reference:
    - title: Alameda County Social Services Agency - General Assistance
      href: https://www.alamedacountysocialservices.org/our-services/Work-and-Money/General-Assistance/index
