name: Test (Optimized)

on: [push, pull_request]

jobs:
  # Run the most memory-intensive integration tests separately with extra swap
  test-heavy-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -e .[dev]
      
      - name: Maximize swap space
        run: |
          sudo swapoff -a
          sudo fallocate -l 14G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h
      
      - name: Run heavy integration tests
        run: |
          # Run the top memory-intensive tests one by one
          echo "Testing NC SCCA integration..."
          policyengine-core test policyengine_us/tests/policy/baseline/gov/states/nc/ncdhhs/scca/integration.yaml -c policyengine_us || true
          
          echo "Testing MO pension integration..."
          policyengine-core test "policyengine_us/tests/policy/baseline/gov/states/mo/tax/income/deductions/mo_pension_and_ss_or_ssd_deduction/integration_tests/" -c policyengine_us || true
          
          echo "Testing IA tax integration..."
          policyengine-core test policyengine_us/tests/policy/baseline/gov/states/ia/tax/income/ia_integration.yaml -c policyengine_us || true
          
          echo "Testing IL AABD integration..."
          policyengine-core test policyengine_us/tests/policy/baseline/gov/states/il/dhs/aabd/integration.yaml -c policyengine_us || true
          
          echo "Testing MA tax integration..."
          policyengine-core test policyengine_us/tests/policy/baseline/gov/states/ma/tax/income/integration_ma.yaml -c policyengine_us || true

  # Run other integration tests in parallel chunks
  test-integration-chunks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunk:
          - name: "states-1"
            paths: "mt ky de ms"
          - name: "states-2"
            paths: "va la md ct oh"
          - name: "states-3"
            paths: "nm ar mi id"
          - name: "irs"
            paths: "irs"
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -e .[dev]
      
      - name: Add swap space
        run: |
          sudo swapoff -a
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h
      
      - name: Run integration tests for ${{ matrix.chunk.name }}
        run: |
          for state in ${{ matrix.chunk.paths }}; do
            echo "Testing $state integration tests..."
            if [ "$state" = "irs" ]; then
              find policyengine_us/tests/policy/baseline/gov/irs -name "*integration*.yaml" -exec policyengine-core test {} -c policyengine_us \;
            else
              find policyengine_us/tests/policy/baseline/gov/states/$state -name "*integration*.yaml" -exec policyengine-core test {} -c policyengine_us \;
            fi
          done

  # Run regular tests in parallel
  test-regular:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_group:
          - name: "structural"
            cmd: "make test-yaml-structural"
          - name: "states-small-1"
            states: "al ak az ar co ct de fl ga hi"
          - name: "states-small-2"
            states: "id in ks ky la me md ma mi mn"
          - name: "states-small-3"
            states: "ms mo mt ne nv nh nj nm ny nd"
          - name: "states-small-4"
            states: "oh ok or pa ri sc sd tn tx ut"
          - name: "states-small-5"
            states: "vt va wa wv wi wy dc"
          - name: "federal-non-irs"
            path: "policyengine_us/tests/policy/baseline/gov/hhs"
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -e .[dev]
      
      - name: Add swap space
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
      
      - name: Run tests for ${{ matrix.test_group.name }}
        run: |
          if [ "${{ matrix.test_group.cmd }}" ]; then
            ${{ matrix.test_group.cmd }}
          elif [ "${{ matrix.test_group.states }}" ]; then
            for state in ${{ matrix.test_group.states }}; do
              echo "Testing $state (non-integration)..."
              # Skip integration tests, they're handled separately
              find policyengine_us/tests/policy/baseline/gov/states/$state -name "*.yaml" ! -name "*integration*" -exec policyengine-core test {} -c policyengine_us \;
            done
          elif [ "${{ matrix.test_group.path }}" ]; then
            policyengine-core test ${{ matrix.test_group.path }} -c policyengine_us
          fi

  test-summary:
    needs: [test-heavy-integration, test-integration-chunks, test-regular]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test-heavy-integration.result }}" = "failure" ] || \
             [ "${{ needs.test-integration-chunks.result }}" = "failure" ] || \
             [ "${{ needs.test-regular.result }}" = "failure" ]; then
            echo "Some tests failed. Check individual job results."
            exit 1
          else
            echo "All tests passed!"
          fi